apiVersion: v1
kind: Service
metadata:
  name: mappingservice
  labels:
    app: mappingservice
spec:
  type: LoadBalancer 
  ports:
  - port: 3002
    targetPort: 3002
    name: http
    protocol: TCP
  selector:
    app: mappingservice
