apiVersion: v1
kind: Service
metadata:
  name: crud
  labels:
    app: crud
spec:
  type: LoadBalancer 
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
  selector:
    app: crud
